Repository LegalMate/hyacinth, pull requests merged in 2023-01, with the labels that each got.

#4 L-265: Switch from Pipenv to Poetry
  .github/workflows/basic.yml
  Pipfile
  Pipfile.lock
  hyacinth/__init__.py
Labels: size/M

#5 L-292: Support file uploads
  hyacinth/session.py
Labels: size/L

#6 L-156: Basic support for API rate limits
  hyacinth/session.py
Labels: size/M

#7 nfranchise/l-315 Bug fix for rate limit wrapper and paginated resource
  hyacinth/__init__.py
  hyacinth/session.py
Labels: size/S

#8 L-311: Add support for POSTing new Folders
  hyacinth/session.py
Labels: size/S

#9 L-313: Error handling
  hyacinth/__init__.py
  hyacinth/session.py
Labels: size/XS

#10 L-321: Support Folder deletion
  hyacinth/session.py
Labels: size/XS
