Repository LegalMate/hyacinth, pull requests merged in 2023-02, with the labels that each got.

#11 L-344: Support for getting folder and folders
  hyacinth/session.py
Labels: size/M

#12 L-360, L-365: Matter PATCH, Custom Field GET
  hyacinth/session.py
Labels: size/S

#13 L-362: POST Calendar Events
  hyacinth/session.py
Labels: size/S

#14 L-363: POST Notes
  hyacinth/session.py
Labels: size/XS

#15 L-408: Fix rate limit logging
  hyacinth/session.py
Labels: size/XS

#16 L-301: Fix tests
  .github/workflows/basic.yml
  README.md
  poetry.lock
  pyproject.toml
  test/__init__.py
  test/test_session.py
Labels: size/L

#17 L-368: POST Webhooks
  hyacinth/session.py
Labels: size/S
