Repository LegalMate/hyacinth, pull requests merged in 2023-04, with the labels that each got.

#19 L-572: Fix upload_document bug with params
  hyacinth/session.py
Labels: bug, size/XS

#20 L-576: Patch calendar entry endpoint
  hyacinth/session.py
Labels: size/XS, needs review

#21 L-545: Save new OAuth2 tokens after refresh
  .github/workflows/basic.yml
  README.md
  hyacinth/session.py
  poetry.lock
  pyproject.toml
  test/test_session.py
Labels: size/M, needs review

#22 L-587: POST tasks to Clio
  hyacinth/session.py
Labels: size/XS, needs review

#23 L-383: Get document templates and post document automations
  hyacinth/session.py
Labels: size/S, needs review

#24 L-597: Support for creating matters, activities, and activity descriptions
  hyacinth/session.py
Labels: size/M, in progress

#26 L-650: Support multipart file uploads on Clio
  hyacinth/session.py
  poetry.lock
  pyproject.toml
Labels: size/L
