Repository LegalMate/hyacinth, pull requests merged in 2023-05, with the labels that each got.

#27 L-662: Implement upload_document_async
  hyacinth/session.py
Labels: size/M

#25 L-302: Support for async requests
  hyacinth/__init__.py
  hyacinth/async_session.py
  poetry.lock
  pyproject.toml
Labels: size/L

#28 L-726: Increase PUT timeout for clio_async_session.upload_document
  hyacinth/async_session.py
  hyacinth/session.py
Labels: size/XS

#29 L-742: Add model specific fields to be returned in webhooks we create
  .gitignore
  hyacinth/session.py
Labels: size/S, needs review

#31 L-811: Bug where hyacinth tries to return json when the endpoint returns bytes
  hyacinth/session.py
  poetry.lock
Labels: bug, size/XS, needs review

#32 L-814: Add expires_at to post_webhook, but it is optional
  hyacinth/session.py
Labels: size/XS, in progress
