Repository LegalMate/hyacinth, pull requests merged in 2023-06, with the labels that each got.

#33 added delete document function
  hyacinth/session.py
Labels: size/M

#34 L-864: Fix for some previously added endpoints and support for Custom Actions.
  hyacinth/session.py
Labels: size/M, needs review

#35 L-895: Support for verifying custom actions
  hyacinth/session.py
Labels: size/S, needs review
