Repository LegalMate/hyacinth, pull requests merged in 2024-11, with the labels that each got.

#70 L-3167 make activity related methods for async class
  hyacinth/async_session.py
Labels: size/S

#71 L-3180: Fix for logging errors in async client
  hyacinth/async_session.py
Labels: bug, size/XS

#69 L-3161: Improve parity between sync and async clients
  hyacinth/async_session.py
  poetry.lock
Labels: size/L

#73 Shariq/l 3197
  hyacinth/async_session.py
Labels: size/XS

#74 L-3230: Handle redirects from Clio to S3 in async client
  hyacinth/async_session.py
Labels: bug, size/S

#75 L-3274: Adding context management to async client
  hyacinth/async_session.py
Labels: size/XS
