Repository LegalMate/hyacinth, pull requests merged in 2024-08, with the labels that each got.

#62 L-2893: Add GET matter client
  hyacinth/session.py
Labels: size/XS, needs review

#63 L-2911: Bug: Infrequent base64 encoded API responses from Clio cause errors in our response processing
  hyacinth/session.py
Labels: size/S, needs review

#64 L-2956: Support for Clio Communication model
  hyacinth/session.py
Labels: size/M, needs review
